let data = [
  {
    kbActivityCategories: {
      ContentUpload: "Content Upload",
      ContentUpdate: "Content Update",
      ContentSharing: "Content Sharing",
    },
    kbActivityTypes: {
      ContentUpload: {
        ContentUpload: "Content Upload",
        ContentCreate: "Content Create",
      },
      ContentUpdate: {
        ContentEdit: "Content Edit",
        ContentRename: "Content Rename",
        ContentRestore: "Content Restore",
        ContentMove: "Content Move",
        ContentCopy: "Content Copy",
      },
      ContentSharing: {
        ColloborationAdd: "Colloboration Add",
        ColloborationInvite: "Colloboration Invite",
        ContentShare: "Content Share",
        ColloborationUpdate: "Colloboration Update",
      },
    },
    id: 992,
    name: "Anomalous Activities by Geolocation",
    description:
      "Chart shows anomalous activity details based on the time and distance",
    activityCategory: "Login",
    activityTypes: ["Login"],
    isPredefined: true,
    metricType: "Count",
    anomalyKey: "GeoAnomaly",
    createdDate: 1600488878969,
    updatedDate: 1600488878969,
    lastUpdatedTime: 1600488878969,
    createdUser: "system",
    updatedUser: "system",
  },
  {
    kbActivityCategories: {
      ContentUpload: "Content Upload",
      ContentUpdate: "Content Update",
      ContentSharing: "Content Sharing",
    },
    kbActivityTypes: {
      ContentUpload: {
        ContentUpload: "Content Upload",
        ContentCreate: "Content Create",
      },
      ContentUpdate: {
        ContentEdit: "Content Edit",
        ContentRename: "Content Rename",
        ContentRestore: "Content Restore",
        ContentMove: "Content Move",
        ContentCopy: "Content Copy",
      },
      ContentSharing: {
        ColloborationAdd: "Colloboration Add",
        ColloborationInvite: "Colloboration Invite",
        ContentShare: "Content Share",
        ColloborationUpdate: "Colloboration Update",
      },
    },
    id: 993,
    name: "Anomalous Downloads by Count",
    description:
      "Chart shows a summary count of anomalous users over time by count of downloaded files.",
    activityCategory: "ContentDownload",
    activityTypes: ["ContentDownload"],
    isPredefined: true,
    metricType: "Count",
    anomalyKey: "DownloadCount",
    createdDate: 1600488878977,
    updatedDate: 1600488878977,
    lastUpdatedTime: 1600488878977,
    createdUser: "system",
    updatedUser: "system",
  },
  {
    kbActivityCategories: {
      ContentUpload: "Content Upload",
      ContentUpdate: "Content Update",
      ContentSharing: "Content Sharing",
    },
    kbActivityTypes: {
      ContentUpload: {
        ContentUpload: "Content Upload",
        ContentCreate: "Content Create",
      },
      ContentUpdate: {
        ContentEdit: "Content Edit",
        ContentRename: "Content Rename",
        ContentRestore: "Content Restore",
        ContentMove: "Content Move",
        ContentCopy: "Content Copy",
      },
      ContentSharing: {
        ColloborationAdd: "Colloboration Add",
        ColloborationInvite: "Colloboration Invite",
        ContentShare: "Content Share",
        ColloborationUpdate: "Colloboration Update",
      },
    },
    id: 994,
    name: "Anomalous Downloads by Size",
    description:
      "Chart shows a summary count of anomalous users over time by size of downloaded files.",
    activityCategory: "ContentDownload",
    activityTypes: ["ContentDownload"],
    isPredefined: true,
    metricType: "Size",
    anomalyKey: "DownloadSize",
    createdDate: 1600488878980,
    updatedDate: 1600488878980,
    lastUpdatedTime: 1600488878980,
    createdUser: "system",
    updatedUser: "system",
  },
  {
    kbActivityCategories: {
      ContentUpload: "Content Upload",
      ContentUpdate: "Content Update",
      ContentSharing: "Content Sharing",
    },
    kbActivityTypes: {
      ContentUpload: {
        ContentUpload: "Content Upload",
        ContentCreate: "Content Create",
      },
      ContentUpdate: {
        ContentEdit: "Content Edit",
        ContentRename: "Content Rename",
        ContentRestore: "Content Restore",
        ContentMove: "Content Move",
        ContentCopy: "Content Copy",
      },
      ContentSharing: {
        ColloborationAdd: "Colloboration Add",
        ColloborationInvite: "Colloboration Invite",
        ContentShare: "Content Share",
        ColloborationUpdate: "Colloboration Update",
      },
    },
    id: 995,
    name: "Anomalous Content Delete",
    description:
      "Chart shows a summary count of anomalous users over time by count of delete activities.",
    activityCategory: "ContentDelete",
    activityTypes: ["ContentDelete"],
    isPredefined: true,
    metricType: "Count",
    anomalyKey: "ContentDelete",
    createdDate: 1600488878982,
    updatedDate: 1600488878982,
    lastUpdatedTime: 1600488878982,
    createdUser: "system",
    updatedUser: "system",
  },
  {
    kbActivityCategories: {
      ContentUpload: "Content Upload",
      ContentUpdate: "Content Update",
      ContentSharing: "Content Sharing",
    },
    kbActivityTypes: {
      ContentUpload: {
        ContentUpload: "Content Upload",
        ContentCreate: "Content Create",
      },
      ContentUpdate: {
        ContentEdit: "Content Edit",
        ContentRename: "Content Rename",
        ContentRestore: "Content Restore",
        ContentMove: "Content Move",
        ContentCopy: "Content Copy",
      },
      ContentSharing: {
        ColloborationAdd: "Colloboration Add",
        ColloborationInvite: "Colloboration Invite",
        ContentShare: "Content Share",
        ColloborationUpdate: "Colloboration Update",
      },
    },
    id: 996,
    name: "Anomalous Authentications",
    description:
      "Chart shows a summary count of anomalous users over time by count of logins",
    activityCategory: "Login",
    activityTypes: ["Login"],
    isPredefined: true,
    metricType: "Count",
    anomalyKey: "Authentications",
    createdDate: 1600488878984,
    updatedDate: 1600488878984,
    lastUpdatedTime: 1600488878984,
    createdUser: "system",
    updatedUser: "system",
  },
  {
    kbActivityCategories: {
      ContentUpload: "Content Upload",
      ContentUpdate: "Content Update",
      ContentSharing: "Content Sharing",
    },
    kbActivityTypes: {
      ContentUpload: {
        ContentUpload: "Content Upload",
        ContentCreate: "Content Create",
      },
      ContentUpdate: {
        ContentEdit: "Content Edit",
        ContentRename: "Content Rename",
        ContentRestore: "Content Restore",
        ContentMove: "Content Move",
        ContentCopy: "Content Copy",
      },
      ContentSharing: {
        ColloborationAdd: "Colloboration Add",
        ColloborationInvite: "Colloboration Invite",
        ContentShare: "Content Share",
        ColloborationUpdate: "Colloboration Update",
      },
    },
    id: 997,
    name: "ContentUpload",
    description: "ContentUpload",
    activityCategory: "ContentUpload",
    activityTypes: ["ContentUpload", "ContentCreate"],
    isPredefined: false,
    metricType: "Count",
    anomalyKey: "ContentUpload_997",
    createdDate: 1600672367267,
    updatedDate: 1600672367279,
    lastUpdatedTime: 1600672367279,
    createdUser: "vjanapati@ciphercloud.com",
    updatedUser: "vjanapati@ciphercloud.com",
  },
  {
    kbActivityCategories: {
      ContentUpload: "Content Upload",
      ContentUpdate: "Content Update",
      ContentSharing: "Content Sharing",
    },
    kbActivityTypes: {
      ContentUpload: {
        ContentUpload: "Content Upload",
        ContentCreate: "Content Create",
      },
      ContentUpdate: {
        ContentEdit: "Content Edit",
        ContentRename: "Content Rename",
        ContentRestore: "Content Restore",
        ContentMove: "Content Move",
        ContentCopy: "Content Copy",
      },
      ContentSharing: {
        ColloborationAdd: "Colloboration Add",
        ColloborationInvite: "Colloboration Invite",
        ContentShare: "Content Share",
        ColloborationUpdate: "Colloboration Update",
      },
    },
    id: 998,
    name: "ContentUpdate",
    description: "ContentUpdate",
    activityCategory: "ContentUpdate",
    activityTypes: [
      "ContentEdit",
      "ContentRename",
      "ContentRestore",
      "ContentMove",
      "ContentCopy",
    ],
    isPredefined: false,
    metricType: "Count",
    anomalyKey: "ContentUpdate_998",
    createdDate: 1600672395508,
    updatedDate: 1600672395513,
    lastUpdatedTime: 1600672395513,
    createdUser: "vjanapati@ciphercloud.com",
    updatedUser: "vjanapati@ciphercloud.com",
  },
  {
    kbActivityCategories: {
      ContentUpload: "Content Upload",
      ContentUpdate: "Content Update",
      ContentSharing: "Content Sharing",
    },
    kbActivityTypes: {
      ContentUpload: {
        ContentUpload: "Content Upload",
        ContentCreate: "Content Create",
      },
      ContentUpdate: {
        ContentEdit: "Content Edit",
        ContentRename: "Content Rename",
        ContentRestore: "Content Restore",
        ContentMove: "Content Move",
        ContentCopy: "Content Copy",
      },
      ContentSharing: {
        ColloborationAdd: "Colloboration Add",
        ColloborationInvite: "Colloboration Invite",
        ContentShare: "Content Share",
        ColloborationUpdate: "Colloboration Update",
      },
    },
    id: 999,
    name: "ContentShare",
    description: "ContentShare",
    activityCategory: "ContentSharing",
    activityTypes: [
      "ColloborationAdd",
      "ColloborationInvite",
      "ContentShare",
      "ColloborationUpdate",
    ],
    isPredefined: false,
    metricType: "Count",
    anomalyKey: "ContentSharing_999",
    createdDate: 1600672412406,
    updatedDate: 1600672412410,
    lastUpdatedTime: 1600672412410,
    createdUser: "vjanapati@ciphercloud.com",
    updatedUser: "vjanapati@ciphercloud.com",
  },
  {
    kbActivityCategories: {
      ContentUpload: "Content Upload",
      ContentUpdate: "Content Update",
      ContentSharing: "Content Sharing",
    },
    kbActivityTypes: {
      ContentUpload: {
        ContentUpload: "Content Upload",
        ContentCreate: "Content Create",
      },
      ContentUpdate: {
        ContentEdit: "Content Edit",
        ContentRename: "Content Rename",
        ContentRestore: "Content Restore",
        ContentMove: "Content Move",
        ContentCopy: "Content Copy",
      },
      ContentSharing: {
        ColloborationAdd: "Colloboration Add",
        ColloborationInvite: "Colloboration Invite",
        ContentShare: "Content Share",
        ColloborationUpdate: "Colloboration Update",
      },
    },
    id: 1992,
    name: "Anomalous Activities by Geolocation",
    description:
      "Chart shows anomalous activity details based on the time and distance",
    activityCategory: "Login",
    activityTypes: ["Login"],
    isPredefined: true,
    metricType: "Count",
    anomalyKey: "GeoAnomaly",
    createdDate: 1600774496095,
    updatedDate: 1600774496095,
    lastUpdatedTime: 1600774496095,
    createdUser: "system",
    updatedUser: "system",
  },
  {
    kbActivityCategories: {
      ContentUpload: "Content Upload",
      ContentUpdate: "Content Update",
      ContentSharing: "Content Sharing",
    },
    kbActivityTypes: {
      ContentUpload: {
        ContentUpload: "Content Upload",
        ContentCreate: "Content Create",
      },
      ContentUpdate: {
        ContentEdit: "Content Edit",
        ContentRename: "Content Rename",
        ContentRestore: "Content Restore",
        ContentMove: "Content Move",
        ContentCopy: "Content Copy",
      },
      ContentSharing: {
        ColloborationAdd: "Colloboration Add",
        ColloborationInvite: "Colloboration Invite",
        ContentShare: "Content Share",
        ColloborationUpdate: "Colloboration Update",
      },
    },
    id: 1993,
    name: "Anomalous Downloads by Count",
    description:
      "Chart shows a summary count of anomalous users over time by count of downloaded files.",
    activityCategory: "ContentDownload",
    activityTypes: ["ContentDownload"],
    isPredefined: true,
    metricType: "Count",
    anomalyKey: "DownloadCount",
    createdDate: 1600774496107,
    updatedDate: 1600774496107,
    lastUpdatedTime: 1600774496107,
    createdUser: "system",
    updatedUser: "system",
  },
  {
    kbActivityCategories: {
      ContentUpload: "Content Upload",
      ContentUpdate: "Content Update",
      ContentSharing: "Content Sharing",
    },
    kbActivityTypes: {
      ContentUpload: {
        ContentUpload: "Content Upload",
        ContentCreate: "Content Create",
      },
      ContentUpdate: {
        ContentEdit: "Content Edit",
        ContentRename: "Content Rename",
        ContentRestore: "Content Restore",
        ContentMove: "Content Move",
        ContentCopy: "Content Copy",
      },
      ContentSharing: {
        ColloborationAdd: "Colloboration Add",
        ColloborationInvite: "Colloboration Invite",
        ContentShare: "Content Share",
        ColloborationUpdate: "Colloboration Update",
      },
    },
    id: 1994,
    name: "Anomalous Downloads by Size",
    description:
      "Chart shows a summary count of anomalous users over time by size of downloaded files.",
    activityCategory: "ContentDownload",
    activityTypes: ["ContentDownload"],
    isPredefined: true,
    metricType: "Size",
    anomalyKey: "DownloadSize",
    createdDate: 1600774496110,
    updatedDate: 1600774496110,
    lastUpdatedTime: 1600774496110,
    createdUser: "system",
    updatedUser: "system",
  },
  {
    kbActivityCategories: {
      ContentUpload: "Content Upload",
      ContentUpdate: "Content Update",
      ContentSharing: "Content Sharing",
    },
    kbActivityTypes: {
      ContentUpload: {
        ContentUpload: "Content Upload",
        ContentCreate: "Content Create",
      },
      ContentUpdate: {
        ContentEdit: "Content Edit",
        ContentRename: "Content Rename",
        ContentRestore: "Content Restore",
        ContentMove: "Content Move",
        ContentCopy: "Content Copy",
      },
      ContentSharing: {
        ColloborationAdd: "Colloboration Add",
        ColloborationInvite: "Colloboration Invite",
        ContentShare: "Content Share",
        ColloborationUpdate: "Colloboration Update",
      },
    },
    id: 1995,
    name: "Anomalous Content Delete",
    description:
      "Chart shows a summary count of anomalous users over time by count of delete activities.",
    activityCategory: "ContentDelete",
    activityTypes: ["ContentDelete"],
    isPredefined: true,
    metricType: "Count",
    anomalyKey: "ContentDelete",
    createdDate: 1600774496114,
    updatedDate: 1600774496114,
    lastUpdatedTime: 1600774496114,
    createdUser: "system",
    updatedUser: "system",
  },
  {
    kbActivityCategories: {
      ContentUpload: "Content Upload",
      ContentUpdate: "Content Update",
      ContentSharing: "Content Sharing",
    },
    kbActivityTypes: {
      ContentUpload: {
        ContentUpload: "Content Upload",
        ContentCreate: "Content Create",
      },
      ContentUpdate: {
        ContentEdit: "Content Edit",
        ContentRename: "Content Rename",
        ContentRestore: "Content Restore",
        ContentMove: "Content Move",
        ContentCopy: "Content Copy",
      },
      ContentSharing: {
        ColloborationAdd: "Colloboration Add",
        ColloborationInvite: "Colloboration Invite",
        ContentShare: "Content Share",
        ColloborationUpdate: "Colloboration Update",
      },
    },
    id: 1996,
    name: "Anomalous Authentications",
    description:
      "Chart shows a summary count of anomalous users over time by count of logins",
    activityCategory: "Login",
    activityTypes: ["Login"],
    isPredefined: true,
    metricType: "Count",
    anomalyKey: "Authentications",
    createdDate: 1600774496116,
    updatedDate: 1600774496116,
    lastUpdatedTime: 1600774496116,
    createdUser: "system",
    updatedUser: "system",
  },
];

let names = data.map((item) => item.name);
console.log(names);
